[project]
name = "booklab"
dynamic = ["version"]
description = "Vectorial ma=s f4om Lidar(C) data.."

authors = [
    {name = "Petre Iordanescu", email = "petre.iordanescu@gmail.com"},
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "GNU"}

dependencies = [
    "mkdocs>=1.6.1"
    ]


[project.urls]
HomePage = "http://booklab.renware.eu/"
DevPage = "http://dev.renware.eu/booklab/"



[tool.pdm]
distribution = true

[tool.pdm.scripts]
gen_tech_doc = {shell = "src/booklab/scripts/gen-api-doc.sh"}
gen_app_routes = {shell = "src/booklab/scripts/gen-app-routes.sh"}
gen_static_site = {shell = "src/booklab/scripts/master_site_build.sh"}
build_site = { composite = [
    "gen_tech_doc",
    "gen_app_routes",
    "gen_static_site"
    ] }
build_all = { composite = [
    "gen_tech_doc",
    "gen_app_routes",
    "gen_static_site",
    "pdm build"
    ] }
bklab_srv = {shell = "src/booklab/scripts/server-run.sh"}  # run booklabd wsgi server


[tool.pdm.version]
source = "file"
path = "src/booklab/__version__.py"


[project.scripts]
booklab = "booklab.__main__:main"


[build-system]
requires = ["pdm-backend >= 2.4.0"]
build-backend = "pdm.backend"


[dependency-groups]
test = [
    "pytest>=8.4.2",
    ]
dev = [
    "pydoc-markdown>=4.8.2",
    "docopt>=0.6.2",
    "python-dotenv>=1.1.1",
    "pylint>=4.0.2",
    "black>=25.9.0",
    "bpython>=0.26",
    "pex>=2.0.3",
]
