[project]
name = "lidarmap"
dynamic = ["version"]
description = "Vectorial maps from Lidar(C) data."

authors = [
    {name = "Petre Iordanescu", email = "petre.iordanescu@gmail.com"},
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

dependencies = [
    "mkdocs>=1.6.1",
    "maturin>=1.12.4"
    ]


[project.urls]
HomePage = "...tbd..."
DevPage = "http://dev.renware.eu/lidarmap/"


[tool.pdm]
distribution = true


[tool.pdm.version]
source = "file"
path = "src/__version__.py"


[project.scripts]
lidarmap = "__main__:main"


[build-system]
requires = ["pdm-backend >= 2.4.0"]
build-backend = "pdm.backend"


[dependency-groups]
test = [
    "pytest>=8.4.2",
    ]
dev = [
    "pydoc-markdown>=4.8.2",
    "docopt>=0.6.2",
    "python-dotenv>=1.1.1",
    "pylint>=4.0.2",
    "black>=25.9.0",
    "bpython>=0.26",
    "pex>=2.0.3",
]
