[project]
name = "lidarmap"
dynamic = ["version"]
description = "Vectorial maps from Lidar(C) data."

authors = [
    {name = "Petre Iordanescu", email = "petre.iordanescu@gmail.com"},
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

dependencies = [
    "mkdocs>=1.6.1",
    "maturin>=1.12.4",
    "markdown-exec>=1.12.1",
    "mkdocs-include-markdown-plugin>=7.2.1",
    "pymdown-extensions>=10.21",
    "mkdocs-material>=9.7.3"
    ]


[project.urls]
HomePage = "...tbd..."
DevPage = "http://dev.renware.eu/lidarmap/"


[tool.pdm]
distribution = true


[tool.pdm.scripts]
#TODO all lines need be revised & updated for LidarMap system
gen_tech_doc = {shell = "src/booklab/scripts/gen-api-doc.sh"}
gen_app_routes = {shell = "src/booklab/scripts/gen-app-routes.sh"}
gen_static_site = {shell = "src/booklab/scripts/master_site_build.sh"}
build_site = { composite = [
    "gen_tech_doc",
    "gen_app_routes",
    "gen_static_site"
    ] }


[tool.pdm.version]
source = "file"
path = "src/__version__.py"


[project.scripts]
lidarmap = "__main__:main"


[build-system]
requires = ["pdm-backend >= 2.4.0"]
build-backend = "pdm.backend"


[dependency-groups]
test = [
    "pytest>=8.4.2",
    ]
dev = [
    "pydoc-markdown>=4.8.2",
    "docopt>=0.6.2",
    "python-dotenv>=1.1.1",
    "pylint>=4.0.2",
    "black>=25.9.0",
    "bpython>=0.26",
    "pex>=2.0.3",
]
